'''
PROJECT:     winexports
LICENSE:     MIT (https://spdx.org/licenses/MIT)
PURPOSE:     Generate Hugo content pages and aggregated data files from DLL export JSONs
COPYRIGHT:   Copyright 2026 Mark Jansen <mark.jansen@reactos.org>

Usage:
    python scripts/generate_hugo_content.py           # clean then generate
    python scripts/generate_hugo_content.py --clean   # clean only

Generates:
    content/_index.md                   - site home page with version table
    data/versions.json                  - version metadata (label, desc, order) for Hugo templates
    data/dlls/{safe_name}.json          - per-DLL aggregated data across all Windows versions
    content/dlls/{safe_name}.md         - Hugo content page per DLL
    content/functions/{slug}.md         - Hugo page per multi-DLL function (hidden from nav)
    static/data/fn/{slug}.json          - per-function cross-reference (multi-DLL only)
    static/data/function_names.json     - [[fname, path], ...] for client-side search

Only functions exported by two or more DLLs get a dedicated function page.
Single-DLL functions are already fully described by their DLL's export page.
'''

import argparse
import hashlib
import json
import re
import shutil
import stat
from pathlib import Path

SCRIPTDIR = Path(__file__).parent
ROOT = SCRIPTDIR.parent
EXPORTS_DIR = ROOT / 'data' / 'exports'
DLLS_DATA_DIR = ROOT / 'data' / 'dlls'
VERSIONS_DATA_FILE = ROOT / 'data' / 'versions.json'
CONTENT_HOME = ROOT / 'content' / '_index.md'
CONTENT_DLLS_DIR = ROOT / 'content' / 'dlls'
CONTENT_FUNCTIONS_DIR = ROOT / 'content' / 'functions'
STATIC_DATA_DIR = ROOT / 'static' / 'data'

# Human-readable metadata for each known version key.
# label: short form used as column header in tables.
# desc:  longer form used as tooltip / home page description.
_KNOWN_VERSIONS = {
    'nt51_x86':        ('NT 5.1 x86',  'Windows XP x86 (build 2600)'),
    'nt52_x86':        ('NT 5.2 x86',  'Windows Server 2003 x86 (build 3790)'),
    'nt60_x86':        ('NT 6.0 x86',  'Windows Vista x86 (build 6002)'),
    'nt61_x86':        ('NT 6.1 x86',  'Windows 7 x86 (build 7601)'),
    'nt61_x64':        ('NT 6.1 x64',  'Windows 7 x64 (build 7601)'),
    'nt63_x86':        ('NT 6.3 x86',  'Windows 8.1 x86 (build 9600)'),
    'nt63_x64':        ('NT 6.3 x64',  'Windows 8.1 x64 (build 9600)'),
    'nt100_x64_19041': ('NT 10.0 x64', 'Windows 10 x64 (build 19041)'),
    'nt100_x64_26200': ('NT 10.0 x64', 'Windows 11 x64 (build 26200)'),
}


def _version_meta(ver):
    """Return (label, desc) for a version key, falling back to a derived value."""
    if ver in _KNOWN_VERSIONS:
        return _KNOWN_VERSIONS[ver]
    m = re.fullmatch(r'nt(\d+)_(x86|x64)(?:_(\d+))?', ver)
    if m:
        nt = m.group(1)
        arch = m.group(2)
        build = m.group(3)
        label = f'NT {nt} {arch}' + (f' b{build}' if build else '')
        desc = f'NT {nt} {arch}' + (f' (build {build})' if build else '')
        return label, desc
    return ver, ver


def _version_sort_key(name):
    """Sort key for nt{ver}_{arch}[_{build}] directory names (oldest first)."""
    m = re.fullmatch(r'nt(\d+)_(x86|x64)(?:_(\d+))?', name)
    if not m:
        return (float('inf'), 0, 0)
    arch_rank = {'x86': 0, 'x64': 1}.get(m.group(2), 99)
    return (int(m.group(1)), arch_rank, int(m.group(3) or 0))


def get_version_order():
    """Return sorted list of version directory names found in data/exports/."""
    dirs = [d.name for d in EXPORTS_DIR.iterdir() if d.is_dir()]
    return sorted(dirs, key=_version_sort_key)

# Max characters in a slug before a hash suffix is added.
# Keeps filenames well within git/filesystem path limits.
MAX_SLUG_LEN = 60

DLL_CONTENT_TEMPLATE = """\
---
# This file is auto-generated by scripts/generate_hugo_content.py
title: "{dll_name}"
datakey: "{safe_name}"
weight: {weight}
---

{{{{< dllexports >}}}}
"""


def safe_name(name):
    """Convert a name to a safe key usable as a Hugo data file name and URL slug."""
    return re.sub(r'[^a-z0-9_]', '_', name.lower())


def make_slug(fname):
    """
    Convert a function name to a URL/filesystem-safe slug.

    Long slugs (> MAX_SLUG_LEN chars) are truncated and given an 8-char MD5
    suffix to keep them unique and within filesystem path limits.
    """
    base = safe_name(fname) or 'fn'
    if len(base) <= MAX_SLUG_LEN:
        return base
    h = hashlib.md5(fname.encode('utf-8')).hexdigest()[:8]
    return base[:MAX_SLUG_LEN].rstrip('_') + '_' + h


def build_slug_map(func_names):
    """
    Assign a unique URL slug to every function name in func_names.

    Collisions (two names producing the same make_slug result) are resolved
    by giving every member of the collision group an 8-char MD5 suffix.
    Slugs are deterministic across regenerations.

    Returns: dict  fname -> slug
    """
    groups = {}
    for fname in func_names:
        base = make_slug(fname)
        groups.setdefault(base, []).append(fname)

    slug_map = {}
    for base, names in groups.items():
        if len(names) == 1:
            slug_map[names[0]] = base
        else:
            for fname in names:
                h = hashlib.md5(fname.encode('utf-8')).hexdigest()[:8]
                slug_map[fname] = base[:MAX_SLUG_LEN].rstrip('_') + '_' + h

    return slug_map


def natural_key(s):
    return [int(c) if c.isdigit() else c.lower() for c in re.split(r'(\d+)', s)]


def _clear_generated_md(directory, keep):
    """Delete all *.md files in directory except those in keep."""
    directory.mkdir(parents=True, exist_ok=True)
    for f in directory.glob('*.md'):
        if f.name not in keep:
            f.unlink()


def clean_output_dirs():
    """
    Remove all previously generated files before regeneration.

    content/_index.md and data/versions.json are fully generated.
    content/dlls/ is fully generated (including its _index.md).
    content/functions/ is fully maintained; only its generated *.md files
    from previous runs are cleaned up (fn.md and _index.md are preserved).
    """
    def _on_error(func, path, _exc):
        # Clear read-only flag and retry; warns if still locked.
        try:
            Path(path).chmod(stat.S_IWRITE)
            func(path)
        except PermissionError:
            print(f'  Warning: could not delete {path} (file in use — stop Hugo server first)')

    # Directories that can be wiped entirely
    for d in [DLLS_DATA_DIR, CONTENT_DLLS_DIR, STATIC_DATA_DIR / 'fn']:
        if d.exists():
            shutil.rmtree(d, onerror=_on_error)
        d.mkdir(parents=True)

    # content/functions/ keeps its hand-maintained files
    _clear_generated_md(CONTENT_FUNCTIONS_DIR, keep={'_index.md', 'fn.md'})

    for f in [CONTENT_HOME, VERSIONS_DATA_FILE, STATIC_DATA_DIR / 'function_names.json']:
        if f.exists():
            f.unlink()

    public = ROOT / 'public'
    if public.exists():
        shutil.rmtree(public, onerror=_on_error)

    print('  Cleaned output directories')


def load_all_exports():
    """Read every JSON file from data/exports/{version}/ and return aggregated dict."""

    available = get_version_order()

    # all_dlls[dll_name][version] = {FileVersion, FileDescription, exports:[...]}
    all_dlls = {}

    for version in available:
        version_dir = EXPORTS_DIR / version
        for json_file in sorted(version_dir.glob('*.json'), key=lambda p: natural_key(p.name)):
            dll_name = json_file.stem  # e.g. "advapi32.dll"
            with open(json_file, encoding='utf-8') as f:
                data = json.load(f)
            if dll_name not in all_dlls:
                all_dlls[dll_name] = {}
            all_dlls[dll_name][version] = {
                'FileVersion': data.get('FileVersion', ''),
                'FileDescription': data.get('FileDescription', ''),
                'exports': data.get('exports', []),
            }

    return all_dlls, available


def generate_dll_data(all_dlls):
    """Write one JSON file per DLL into data/dlls/."""
    for dll_name, versions in all_dlls.items():
        sname = safe_name(dll_name)
        out = {'name': dll_name, 'versions': versions}
        with open(DLLS_DATA_DIR / f'{sname}.json', 'w', encoding='utf-8') as f:
            json.dump(out, f, separators=(',', ':'))

    print(f'  Written {len(all_dlls)} DLL data files to {DLLS_DATA_DIR}')


def generate_dll_content(all_dlls):
    """Write one Hugo markdown page per DLL into content/dlls/, plus the section index."""
    # Section index — controls the sidebar title and position
    with open(CONTENT_DLLS_DIR / '_index.md', 'w', encoding='utf-8') as f:
        f.write('---\n# This file is auto-generated by scripts/generate_hugo_content.py\n'
                'title: "DLLs"\nweight: 2\n---\n')

    sorted_dlls = sorted(all_dlls.keys(), key=natural_key)
    for weight, dll_name in enumerate(sorted_dlls, start=1):
        sname = safe_name(dll_name)
        content = DLL_CONTENT_TEMPLATE.format(
            dll_name=dll_name,
            safe_name=sname,
            weight=weight,
        )
        with open(CONTENT_DLLS_DIR / f'{sname}.md', 'w', encoding='utf-8') as f:
            f.write(content)

    print(f'  Written {len(all_dlls)} content pages to {CONTENT_DLLS_DIR}')


def build_function_index(all_dlls, available_versions):
    """
    Invert the DLL-keyed export data into a function-keyed cross-reference.

    Returns: func_index dict:
        fname -> { dll_name -> { ver_idx -> [ver_idx, ordinal] or [ver_idx, ordinal, forwarder] } }
    """
    ver_idx = {v: i for i, v in enumerate(available_versions)}
    func_index = {}

    for dll_name, versions in all_dlls.items():
        for version in available_versions:
            if version not in versions:
                continue
            vi = ver_idx[version]
            for exp in versions[version]['exports']:
                fname = exp.get('name')
                if not fname:
                    continue
                if fname not in func_index:
                    func_index[fname] = {}
                if dll_name not in func_index[fname]:
                    func_index[fname][dll_name] = {}
                if 'forwarder' in exp:
                    func_index[fname][dll_name][vi] = [vi, exp['ordinal'], exp['forwarder']]
                else:
                    func_index[fname][dll_name][vi] = [vi, exp['ordinal']]

    return func_index


def generate_per_function_data(multi_dll_index, available_versions, slug_map):
    """
    Write one compact JSON file per multi-DLL function into static/data/fn/.

    Format:
    {
      "v": ["nt52_x86", ...],
      "d": [
        ["kernel32.dll", [[ver_idx, ordinal], ...]],
        ["kernelbase.dll", [[ver_idx, ordinal, "KERNEL32.Foo"], ...]]
      ]
    }
    """
    out_dir = STATIC_DATA_DIR / 'fn'
    total_kb = 0
    for fname, dll_map in multi_dll_index.items():
        slug = slug_map[fname]
        dll_entries = []
        for dll_name in sorted(dll_map.keys(), key=str.lower):
            refs = sorted(dll_map[dll_name].values(), key=lambda r: r[0])
            dll_entries.append([dll_name, refs])

        out = {'v': available_versions, 'd': dll_entries}
        out_path = out_dir / f'{slug}.json'
        with open(out_path, 'w', encoding='utf-8') as f:
            json.dump(out, f, separators=(',', ':'))
        total_kb += out_path.stat().st_size // 1024

    print(f'  Written {len(multi_dll_index)} per-function data files to {out_dir} ({total_kb} KB total)')


def generate_function_name_list(func_index, slug_map):
    """
    Write a sorted list of [fname, path] pairs to static/data/function_names.json.

    path is a site-root-relative URL (no leading slash):
      - Multi-DLL functions -> "functions/fn/#{slug}"  (hash-routed detail page)
      - Single-DLL functions -> "dlls/{dll_slug}/"     (DLL export page directly)

    The client prepends the site root URL to get the final link.
    """
    pairs = []
    for fname, dll_map in func_index.items():
        if fname in slug_map:
            path = 'functions/fn/#' + slug_map[fname]
        else:
            dll_name = next(iter(dll_map))
            path = 'dlls/' + safe_name(dll_name) + '/'
        pairs.append([fname, path])

    pairs.sort(key=lambda p: p[0].lower())

    out_path = STATIC_DATA_DIR / 'function_names.json'
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(pairs, f, separators=(',', ':'))
    size_kb = out_path.stat().st_size // 1024
    print(f'  Written {len(pairs)} entries to {out_path} ({size_kb} KB)')


def generate_versions_data(available_versions):
    """
    Write data/versions.json — a dict keyed by version name with label, desc, and order.

    Used by Hugo templates (dllexports.html) to render column headers and tooltips
    without hardcoding the version list.
    """
    out = {}
    for order, ver in enumerate(available_versions):
        label, desc = _version_meta(ver)
        out[ver] = {'key': ver, 'label': label, 'desc': desc, 'order': order}
    with open(VERSIONS_DATA_FILE, 'w', encoding='utf-8') as f:
        json.dump(out, f, indent=2)
    print(f'  Written {len(out)} version entries to {VERSIONS_DATA_FILE}')


def generate_home_content(available_versions):
    """Write content/_index.md — the site home page with an auto-generated version table."""
    rows = []
    for ver in available_versions:
        label, desc = _version_meta(ver)
        rows.append(f'| {label} | {desc} |')
    table = '\n'.join(rows)

    content = (
        '---\n'
        '# This file is auto-generated by scripts/generate_hugo_content.py\n'
        'title: "winexports"\n'
        'weight: 1\n'
        '---\n'
        '\n'
        'This site documents the exported functions of Windows DLLs across multiple\n'
        'Windows versions, making it easy to:\n'
        '\n'
        '- **Find all exports** of a DLL, with their ordinal numbers, for each Windows version\n'
        '- **Track forwarder exports** — functions that redirect to another DLL\n'
        '- **Search by function name** to see which DLLs export it and in which versions\n'
        '\n'
        '## Windows versions covered\n'
        '\n'
        '| Key | Description |\n'
        '|-----|-------------|\n'
        f'{table}\n'
        '\n'
        'Use the sidebar to browse **[DLLs](dlls/)** or search the\n'
        '**[function index](functions/)**.\n'
    )
    with open(CONTENT_HOME, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'  Written {CONTENT_HOME}')


def main():
    parser = argparse.ArgumentParser(
        description='Generate Hugo content for winexports.')
    parser.add_argument(
        '--clean', action='store_true',
        help='Remove all generated files and exit without regenerating.')
    args = parser.parse_args()

    print('Cleaning output directories...')
    clean_output_dirs()
    if args.clean:
        return

    print('Loading export data...')
    all_dlls, available_versions = load_all_exports()
    print(f'  Found {len(all_dlls)} unique DLLs across versions: {available_versions}')

    print('Generating version metadata...')
    generate_versions_data(available_versions)

    print('Generating home page...')
    generate_home_content(available_versions)

    print('Generating DLL data files...')
    generate_dll_data(all_dlls)

    print('Generating DLL content pages...')
    generate_dll_content(all_dlls)

    print('Building function cross-reference index...')
    func_index = build_function_index(all_dlls, available_versions)
    multi_dll_index = {f: d for f, d in func_index.items() if len(d) > 1}
    print(f'  {len(func_index)} unique function names, '
          f'{len(multi_dll_index)} exported by multiple DLLs')

    print('Building slug map...')
    slug_map = build_slug_map(multi_dll_index.keys())
    truncated = sum(1 for s in slug_map.values() if len(s) > MAX_SLUG_LEN)
    print(f'  {truncated} slugs truncated to fit filesystem limits')

    print('Generating per-function data files...')
    generate_per_function_data(multi_dll_index, available_versions, slug_map)

    print('Generating function name list...')
    generate_function_name_list(func_index, slug_map)

    print('Done.')


if __name__ == '__main__':
    main()
